In [2]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np

In [3]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [4]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [5]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322166  196.378250  259.299286  24.206572
2023-03-16  96.599998   99.497650  203.508423  269.810333  25.518412
2023-03-17  97.839996  100.787003  194.253082  272.965607  25.702251
2023-03-20  96.809998  100.390274  196.437836  265.932190  25.877092
2023-03-21  95.930000  104.059937  200.757645  267.446320  26.175831

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135444  196.408041  260.315235  24.264519  ...
2023-03-16  96.690002  100.360521  204.332667  270.161991  25.565369  ...
2023-03-17  98.750000  101.996996  200.499443  276.775377  26.375655  ...
2023-03-20  96.940002  100.915928  197.977087  271.060735  26.000983  ...
2023-03-21  99.459999  104.238461  202.138002  268.638097  26.368661  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455857  191.611544  253.965606  23.739984
2023-03-16  89.720001   95.411420  196.884693  259.074558  24.005751
2023-03-17  96.660004   99.438150  199.168742  271.822690  25.959024
2023-03-20  96.300003   99.299293  197.103186  270.572303  25.592345
2023-03-21  97.000000  100.420022  201.790424  268.520878  26.156849

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [6]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [7]:
df.shape

(752, 25)

In [8]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [9]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303725  510.469119  406.722717  110.174772
std      41.766704   59.267770  163.675090   64.594058   53.493754
min      78.209999   95.322166  194.253082  259.299286   24.206572
25%     112.002502  136.263790  335.573471  365.005562   48.840417
50%     141.760002  164.499832  524.537567  409.369644  116.998009
75%     169.445004  190.765568  646.036652  447.321587  146.969254
max     264.329987  343.448242  788.823792  539.825195  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249595  516.874620  410.145541  111.981672  ...
std      42.878968   60.022627  165.615576   64.914354   54.248785  ...
min      85.480003   96.135444  196.408041  260.315235   24.264519  ...
25%     114.395002  137.528318  337.542217  368.108833   49.556455  ...
50%     144.289993  165.989432  532.766816  412.460406  119.131434  ...
75%     172.049995  192.186486  653.125000  450.570338  148.926131  ...
max     267.079987  348.754481  795.064526  552.242002  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924468  178.153441  510.536992  406.707279  110.223178
std      41.941908   59.299622  164.260020   64.850848   53.622100
min      79.220001   92.455857  191.611544  253.965606   23.739984
25%     112.052500  136.271201  335.474109  364.869627   49.125131
50%     142.730003  164.479669  525.245664  410.068699  117.272922
75%     169.307503  190.554032  643.457737  446.764601  147.766449
max     264.190002  347.095646  789.972167  552.023241  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305582e+07  3.181651e+07  1.695467e+07  2.381801e+07  3.364198e+08
std     2.434075e+07  1.357634e+07  9.409248e+06  1.046420e+07  1.752093e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.670622e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [10]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  647.390015  409.410004  182.640106
2026-03-10  203.229996  307.040009  654.070007  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.859985  404.880005  186.029999
2026-03-12  197.740005  303.549988  638.179993  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.710022  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.750000  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  660.299988  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  659.119995  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  653.500000  406.119995  184.940002  ...
2026-03-13  199.679993  307.690002  629.169983  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.780029  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.559998  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.760010  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.750000  404.630005  184.050003
2026-03-13  198.110001  307.010010  623.890015  401.000000  184.919998

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27496600  23661300  18904300  26808000  160513800

[5 rows x 25 columns]

In [11]:
df["Low"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   86.220001   91.880610  189.516180  253.213401   23.339339
2023-03-16   89.019997   94.717161  194.729748  257.189215   23.872867
2023-03-17   95.940002   99.279458  194.074323  269.927568   25.645301
2023-03-20   92.900002   99.051342  192.296764  263.607245   25.107773
2023-03-21   93.639999  100.390270  196.576842  263.284862   25.358555
...                ...         ...         ...         ...         ...
2026-03-09  189.020004  294.079987  626.780029  403.500000  175.550494
2026-03-10  202.199997  305.570007  649.000000  402.929993  182.000149
2026-03-11  203.630005  305.920013  648.359985  401.589996  184.449997
2026-03-12  196.669998  301.029999  636.900024  401.709991  181.750000
2026-03-13  192.270004  300.440002  609.549988  394.250000  179.940002

[752 rows x 5 columns]

In [18]:
df["Low"]["NVDA"]

Date
2023-03-15     23.339339
2023-03-16     23.872867
2023-03-17     25.645301
2023-03-20     25.107773
2023-03-21     25.358555
                 ...
2026-03-09    175.550494
2026-03-10    182.000149
2026-03-11    184.449997
2026-03-12    181.750000
2026-03-13    179.940002
Name: NVDA, Length: 752, dtype: float64

In [23]:
(df == 0).any().sum()

np.int64(0)

In [ ]:
df["Close"]
close_prices = df["Close"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   89.680000   95.322166  196.378250  259.299286   24.206572
2023-03-16   96.599998   99.497650  203.508423  269.810333   25.518412
2023-03-17   97.839996  100.787003  194.253082  272.965607   25.702251
2023-03-20   96.809998  100.390274  196.437836  265.932190   25.877092
2023-03-21   95.930000  104.059937  200.757645  267.446320   26.175831
...                ...         ...         ...         ...         ...
2026-03-09  202.679993  306.359985  647.390015  409.410004  182.640106
2026-03-10  203.229996  307.040009  654.070007  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.859985  404.880005  186.029999
2026-03-12  197.740005  303.549988  638.179993  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.710022  395.549988  180.250000

[752 rows x 5 columns]