In [2]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np

In [3]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [4]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [5]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322166  196.210220  259.299225  24.206570
2023-03-16  96.599998   99.497650  203.334305  269.810425  25.518412
2023-03-17  97.839996  100.787010  194.086899  272.965637  25.702250
2023-03-20  96.809998  100.390282  196.269791  265.932159  25.877090
2023-03-21  95.930000  104.059944  200.585907  267.446381  26.175827

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135444  196.239986  260.315173  24.264517  ...
2023-03-16  96.690002  100.360521  204.157844  270.162082  25.565369  ...
2023-03-17  98.750000  101.997003  200.327916  276.775408  26.375653  ...
2023-03-20  96.940002  100.915936  197.807725  271.060704  26.000981  ...
2023-03-21  99.459999  104.238469  201.965083  268.638158  26.368657  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455857  191.447592  253.965547  23.739982
2023-03-16  89.720001   95.411420  196.716243  259.074646  24.005751
2023-03-17  96.660004   99.438158  198.998353  271.822721  25.959022
2023-03-20  96.300003   99.299300  196.934572  270.572271  25.592343
2023-03-21  97.000000  100.420030  201.617802  268.520939  26.156845

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [6]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [7]:
df.shape

(752, 25)

In [8]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [9]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303726  510.032443  406.722717  110.174772
std      41.766704   59.267770  163.535076   64.594057   53.493754
min      78.209999   95.322166  194.086899  259.299225   24.206570
25%     112.002502  136.263783  335.286346  365.005585   48.840424
50%     141.760002  164.499825  524.088898  409.369659  116.998005
75%     169.445004  190.765568  645.484024  447.321587  146.969257
max     264.329987  343.448242  788.148987  539.825195  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249596  516.432464  410.145541  111.981672  ...
std      42.878968   60.022627  165.473902   64.914353   54.248785  ...
min      85.480003   96.135444  196.239986  260.315173   24.264517  ...
25%     114.395002  137.528322  337.253424  368.108840   49.556451  ...
50%     144.289993  165.989432  532.311036  412.460406  119.131434  ...
75%     172.049995  192.186486  652.566306  450.570338  148.926131  ...
max     267.079987  348.754481  794.384336  552.242002  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924468  178.153442  510.100257  406.707279  110.223178
std      41.941908   59.299621  164.119505   64.850847   53.622100
min      79.220001   92.455857  191.447592  253.965547   23.739982
25%     112.052500  136.271221  335.187151  364.869627   49.125134
50%     142.730003  164.479669  524.796368  410.068699  117.272922
75%     169.307503  190.554032  642.907274  446.764601  147.766449
max     264.190002  347.095646  789.296390  552.023241  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305591e+07  3.181655e+07  1.695474e+07  2.381806e+07  3.364204e+08
std     2.434066e+07  1.357632e+07  9.409263e+06  1.046421e+07  1.752086e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.670622e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [10]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  646.836182  409.410004  182.640106
2026-03-10  203.229996  307.040009  653.510498  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.299805  404.880005  186.029999
2026-03-12  197.740005  303.549988  637.634094  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.184998  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.195859  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  659.735149  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  658.556170  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  652.940997  406.119995  184.940002  ...
2026-03-13  199.679993  307.690002  628.631733  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.236984  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.000925  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.199915  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.195060  404.630005  184.050003
2026-03-13  198.110001  307.010010  623.356281  401.000000  184.919998

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27561900  23693100  18957600  26848000  160988400

[5 rows x 25 columns]

In [11]:
df["Low"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   86.220001   91.880610  189.354021  253.213341   23.339337
2023-03-16   89.019997   94.717161  194.563141  257.189302   23.872867
2023-03-17   95.940002   99.279466  193.908292  269.927599   25.645299
2023-03-20   92.900002   99.051349  192.132261  263.607214   25.107771
2023-03-21   93.639999  100.390277  196.408681  263.284922   25.358552
...                ...         ...         ...         ...         ...
2026-03-09  189.020004  294.079987  626.243828  403.500000  175.550494
2026-03-10  202.199997  305.570007  648.444828  402.929993  182.000149
2026-03-11  203.630005  305.920013  647.805365  401.589996  184.449997
2026-03-12  196.669998  301.029999  636.355221  401.709991  181.750000
2026-03-13  192.270004  300.440002  609.028522  394.250000  179.940002

[752 rows x 5 columns]

In [12]:
df["Low"]["NVDA"]

Date
2023-03-15     23.339337
2023-03-16     23.872867
2023-03-17     25.645299
2023-03-20     25.107771
2023-03-21     25.358552
                 ...
2026-03-09    175.550494
2026-03-10    182.000149
2026-03-11    184.449997
2026-03-12    181.750000
2026-03-13    179.940002
Name: NVDA, Length: 752, dtype: float64

In [13]:
(df == 0).any().sum()

np.int64(0)

In [14]:
df["Close"]
close_prices = df["Close"]

In [15]:
yf.Ticker("NVDA").news

[{'id': 'd4d35a04-ae9c-4944-a1a7-0c333ea68209',
  'content': {'id': 'd4d35a04-ae9c-4944-a1a7-0c333ea68209',
   'contentType': 'STORY',
   'title': 'The AI trade is fueling the market to record highs despite Iran war',
   'description': '',
   'summary': 'The AI trade has been able to insulate itself from disruptions caused by the Middle East war.',
   'pubDate': '2026-04-19T13:05:40Z',
   'displayTime': '2026-04-19T13:05:40Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2023-06/af3be260-0456-11ee-b9f6-76a9a9ff9b98',
    'originalWidth': 6000,
    'originalHeight': 4152,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/MUjWmJk6_TutXjW7dO112Q--~B/aD00MTUyO3c9NjAwMDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2023-06/af3be260-0456-11ee-b9f6-76a9a9ff9b98',
      'width': 6000,
      'height': 4152,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/zm7okx0ddL3tRKbDj441JA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2023-06/af3be260-0456-11ee-b9f6-76a9a9ff9b98',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/the-ai-trade-is-fueling-the-market-to-record-highs-despite-iran-war-130540185.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/the-ai-trade-is-fueling-the-market-to-record-highs-despite-iran-war-130540185.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'aa97b526-2bda-4e4c-a71f-fdd9225c4157',
  'content': {'id': 'aa97b526-2bda-4e4c-a71f-fdd9225c4157',
   'contentType': 'STORY',
   'title': 'S&P 500 at 7,000: 7 investing rules you must now live by',
   'description': '',
   'summary': '... if you want to be bullish on stocks.',
   'pubDate': '2026-04-19T12:30:15Z',
   'displayTime': '2026-04-19T12:30:15Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/gfXa8W65t.tHiDRgDaTfww--~B/aD01MjA5O3c9NzgxNDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/a976999b-4852-4a8f-9aab-dbb602f225e7',
    'originalWidth': 7814,
    'originalHeight': 5209,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/gfXa8W65t.tHiDRgDaTfww--~B/aD01MjA5O3c9NzgxNDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/a976999b-4852-4a8f-9aab-dbb602f225e7',
      'width': 7814,
      'height': 5209,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/6vtwKweDI4hem8c5kgNIYw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-04/a976999b-4852-4a8f-9aab-dbb602f225e7',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/sp-500-at-7000-7-investing-rules-you-must-now-live-by-123015841.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/sp-500-at-7000-7-investing-rules-you-must-now-live-by-123015841.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '9c505c0f-9b44-37fb-bf35-3d2971575933',
  'content': {'id': '9c505c0f-9b44-37fb-bf35-3d2971575933',
   'contentType': 'STORY',
   'title': "Intel Stock Has Added More Than $137 Billion in Value Since March 30. Here's What Happens Next.",
   'description': '',
   'summary': 'Shares of the chip giant have been on a red-hot run lately, but can it sustain its momentum?',
   'pubDate': '2026-04-19T17:35:00Z',
   'displayTime': '2026-04-19T17:35:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/14f6742139f8114b67347332dea8bdd1',
    'originalWidth': 1400,
    'originalHeight': 840,
    'caption': 'Intel flag flying atop a pole.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/GxJSO_30ndj4kQ3y8Mq6ag--~B/aD04NDA7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/14f6742139f8114b67347332dea8bdd1',
      'width': 1400,
      'height': 840,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/AIOjzEjJZkKiwwSi2Kt8Mg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/14f6742139f8114b67347332dea8bdd1',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/19/intel-stock-added-137-billion-value-what-next/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/intel-stock-added-more-137-173500487.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '2e7063e0-d106-3e32-b9df-4d97e1442b2e',
  'content': {'id': '2e7063e0-d106-3e32-b9df-4d97e1442b2e',
   'contentType': 'STORY',
   'title': "Forget The Chip Boom: Wall Street's 'Ultimate Contrarian Trade' Favors Software For 2026",
   'description': '',
   'summary': 'Technology sector leaders across software and semiconductors are approaching a potential inflection point, as BTIG Chief Market Technician Jonathan Krinsky outlines a contrarian shift favoring software over chip stocks. Extreme Valuation Gap Signals Reversal Setup Krinsky said the spread between software stocks in the S&P 1500 and semiconductor stocks in the SOX index has reached an unprecedented level, with the ratio falling 43% below its 200-day moving average. The software stocks in the S&P 1',
   'pubDate': '2026-04-19T17:31:11Z',
   'displayTime': '2026-04-19T17:31:11Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/Benzinga/8b813b5035875ec2c912e9eeab4d76b6',
    'originalWidth': 1024,
    'originalHeight': 683,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/LmMxyQf_OxPi_LHBIdvJDQ--~B/aD02ODM7dz0xMDI0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Benzinga/8b813b5035875ec2c912e9eeab4d76b6',
      'width': 1024,
      'height': 683,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/52L7dom22Xc9w2fxZnEM8w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/Benzinga/8b813b5035875ec2c912e9eeab4d76b6',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Benzinga',
    'url': 'http://www.benzinga.com/',
    'sourceId': 'Benzinga'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/forget-chip-boom-wall-streets-173111755.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/forget-chip-boom-wall-streets-173111755.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '2d75a16e-329a-3b74-9d4f-d10269066c49',
  'content': {'id': '2d75a16e-329a-3b74-9d4f-d10269066c49',
   'contentType': 'STORY',
   'title': "Prediction: The Biggest Winners of 2026 Are These 5 AI Stocks Nobody's Paying Attention to Right Now",
   'description': '',
   'summary': 'These five under-the-radar infrastructure plays could be your second chance to invest in the backbone of the AI boom.',
   'pubDate': '2026-04-19T17:21:00Z',
   'displayTime': '2026-04-19T17:21:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/ec4551e1d24a9d1c5c10bc2158051834',
    'originalWidth': 1400,
    'originalHeight': 748,
    'caption': 'A human hand and robot hand point to each other. In the middle of both is a scale.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/A_AVpiDgdvz5uJW9rCfaJw--~B/aD03NDg7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/ec4551e1d24a9d1c5c10bc2158051834',
      'width': 1400,
      'height': 748,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/N8.aKtOTOMlVaEjOiTWl_A--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/ec4551e1d24a9d1c5c10bc2158051834',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/19/prediction-the-biggest-winners-of-2026-are-these-5/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/prediction-biggest-winners-2026-5-172100955.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'aafdae9b-aca5-3e56-9d8a-9126c997f538',
  'content': {'id': 'aafdae9b-aca5-3e56-9d8a-9126c997f538',
   'contentType': 'STORY',
   'title': 'This Stock Will Be More Profitable Than Amazon and Meta by 2027',
   'description': '',
   'summary': 'The artificial-intelligence boom has supercharged demand for data-center chips, servers, and the high-bandwidth memory that makes it all run. Tech giants are pouring billions into infrastructure, yet memory supply remains tight. This shortage has created a rare window for one memory specialist to deliver profit growth that outpaces even the biggest names in the sector: ... This Stock Will Be More Profitable Than Amazon and Meta by 2027',
   'pubDate': '2026-04-19T17:09:18Z',
   'displayTime': '2026-04-19T17:09:18Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/1a6dacf696786154757cdeb67478a8d7',
    'originalWidth': 1000,
    'originalHeight': 648,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/kdf9Rhzpo0ED0PH.7z9chg--~B/aD02NDg7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/1a6dacf696786154757cdeb67478a8d7',
      'width': 1000,
      'height': 648,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/oe3Gcgl4.Qhe72LyXyNhEg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/1a6dacf696786154757cdeb67478a8d7',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/04/19/this-stock-will-be-more-profitable-than-amazon-and-meta-by-2027/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/stock-more-profitable-amazon-meta-170918126.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '36949f28-e249-3cd1-87fa-35ec2e7d2077',
  'content': {'id': '36949f28-e249-3cd1-87fa-35ec2e7d2077',
   'contentType': 'STORY',
   'title': 'The Smartest Growth Stocks to Buy With $1,000 Before the Nasdaq Heads Higher',
   'description': '',
   'summary': 'Palo Alto Networks and Sandisk have room to head higher because of their improving business prospects.',
   'pubDate': '2026-04-19T16:46:00Z',
   'displayTime': '2026-04-19T16:46:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/27e7dcbefa9bb5f697a02ca1428dd576',
    'originalWidth': 1200,
    'originalHeight': 800,
    'caption': 'Sandisk company logo written on a red background.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/bP0sKdmo13qYlTds9dc1dw--~B/aD04MDA7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/27e7dcbefa9bb5f697a02ca1428dd576',
      'width': 1200,
      'height': 800,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/K6Pjyz1rYmZpsBLXF41NTg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/27e7dcbefa9bb5f697a02ca1428dd576',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/19/the-smartest-growth-stocks-to-buy-with-1000-before/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/smartest-growth-stocks-buy-1-164600178.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'ae630538-983d-3cef-ab14-907e9ef654df',
  'content': {'id': 'ae630538-983d-3cef-ab14-907e9ef654df',
   'contentType': 'STORY',
   'title': 'Will Nvidia Be Worth $6 Trillion a Year From Now? Wall Street Has a Clear Answer.',
   'description': '',
   'summary': "Nvidia's market cap has slipped back below the $5 trillion milestone it reached last year, but a solid comeback seems in the cards.",
   'pubDate': '2026-04-19T16:44:00Z',
   'displayTime': '2026-04-19T16:44:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/24ce6e7ae6693cf53e72f7b423b04be7',
    'originalWidth': 1400,
    'originalHeight': 840,
    'caption': 'Nvidia company logo displayed on a board outside its headquarters.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/aNicMUCBezrUxSILRnjqJg--~B/aD04NDA7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/24ce6e7ae6693cf53e72f7b423b04be7',
      'width': 1400,
      'height': 840,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/kZJZqbSbLpdI3GUHf4JkJA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/24ce6e7ae6693cf53e72f7b423b04be7',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/19/will-nvidia-be-worth-6-trillion-a-year-from-now-wa/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/nvidia-worth-6-trillion-now-164400772.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '6077b9e6-4344-3071-8035-8a1b06c2bbd6',
  'content': {'id': '6077b9e6-4344-3071-8035-8a1b06c2bbd6',
   'contentType': 'STORY',
   'title': "The Trade Desk CEO Just Put $150 Million of His Own Money Into the Stock. Here's Why That's a Signal You Shouldn't Ignore.",
   'description': '',
   'summary': 'Insiders almost always buy a stock for only one reason.',
   'pubDate': '2026-04-19T16:25:00Z',
   'displayTime': '2026-04-19T16:25:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/7df7220fc9abb711f8d2a586629a20ce',
    'originalWidth': 1200,
    'originalHeight': 800,
    'caption': "The Trade Desk's logo.",
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/3181cV7xT.C6Soq5RwAvnA--~B/aD04MDA7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/7df7220fc9abb711f8d2a586629a20ce',
      'width': 1200,
      'height': 800,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/yw5WV61WROwT6GKP.EL8aw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/7df7220fc9abb711f8d2a586629a20ce',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/19/the-trade-desk-ceo-just-put-150-million-of-his-own/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/trade-desk-ceo-just-put-162500755.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '316e7160-4165-3fc6-846e-d84b7f7eaa99',
  'content': {'id': '316e7160-4165-3fc6-846e-d84b7f7eaa99',
   'contentType': 'STORY',
   'title': "Should You Buy USA Rare Earth While It's Below $20?",
   'description': '',
   'summary': 'USA Rare Earth is beating the stock market in 2026, yet still trades over 45% below a recent high. Should you buy?',
   'pubDate': '2026-04-19T15:20:00Z',
   'displayTime': '2026-04-19T15:20:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/5b90cdd6ab9ecc99ffcb058beb80dc7f',
    'originalWidth': 1400,
    'originalHeight': 933,
    'caption': 'Mining shelves under a blue sky. ',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/yhVTJwNXb_eSgcyil9kRsQ--~B/aD05MzM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/5b90cdd6ab9ecc99ffcb058beb80dc7f',
      'width': 1400,
      'height': 933,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/PhEa5GKv.Umig7tJ_tl8Kg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/5b90cdd6ab9ecc99ffcb058beb80dc7f',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/19/should-you-buy-usa-rare-earth-while-its-below-20/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/buy-usa-rare-earth-while-152000367.html',

In [16]:
headlines = []

for stock in stocks:
    news = yf.Ticker(stock).news
    for article in news:
        headlines.append({
            "ticker": stock,
            "title": article["content"]["title"],
            "date": article["content"]["pubDate"]
        })

In [17]:
# Show all content and metadata for single headline
yf.Ticker("NVDA").news[0]

{'id': 'd4d35a04-ae9c-4944-a1a7-0c333ea68209',
 'content': {'id': 'd4d35a04-ae9c-4944-a1a7-0c333ea68209',
  'contentType': 'STORY',
  'title': 'The AI trade is fueling the market to record highs despite Iran war',
  'description': '',
  'summary': 'The AI trade has been able to insulate itself from disruptions caused by the Middle East war.',
  'pubDate': '2026-04-19T13:05:40Z',
  'displayTime': '2026-04-19T13:05:40Z',
  'isHosted': True,
  'bypassModal': False,
  'previewUrl': None,
  'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2023-06/af3be260-0456-11ee-b9f6-76a9a9ff9b98',
   'originalWidth': 6000,
   'originalHeight': 4152,
   'caption': '',
   'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/MUjWmJk6_TutXjW7dO112Q--~B/aD00MTUyO3c9NjAwMDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2023-06/af3be260-0456-11ee-b9f6-76a9a9ff9b98',
     'width': 6000,
     'height': 4152,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/zm7okx0ddL3tRKbDj441JA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2023-06/af3be260-0456-11ee-b9f6-76a9a9ff9b98',
     'width': 170,
     'height': 128,
     'tag': '170x128'}]},
  'provider': {'displayName': 'Yahoo Finance',
   'url': 'http://finance.yahoo.com/',
   'sourceId': 'yahoofinance.com'},
  'canonicalUrl': {'url': 'https://finance.yahoo.com/news/the-ai-trade-is-fueling-the-market-to-record-highs-despite-iran-war-130540185.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/the-ai-trade-is-fueling-the-market-to-record-highs-despite-iran-war-130540185.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'metadata': {'editorsPick': True},
  'finance': {'premiumFinance': {'isPremiumNews': False,
    'isPremiumFreeNews': False}},
  'storyline': None}}

In [18]:
headlines[0]

{'ticker': 'NVDA',
 'title': 'The AI trade is fueling the market to record highs despite Iran war',
 'date': '2026-04-19T13:05:40Z'}

In [19]:
len(headlines)

50

In [20]:
headline_data = pd.DataFrame(headlines)

In [21]:
headline_data.head()

,ticker,title,date
0,NVDA,The AI trade is fueling the market to record h...,2026-04-19T13:05:40Z
1,NVDA,"S&P 500 at 7,000: 7 investing rules you must n...",2026-04-19T12:30:15Z
2,NVDA,Intel Stock Has Added More Than $137 Billion i...,2026-04-19T17:35:00Z
3,NVDA,Forget The Chip Boom: Wall Street's 'Ultimate ...,2026-04-19T17:31:11Z
4,NVDA,Prediction: The Biggest Winners of 2026 Are Th...,2026-04-19T17:21:00Z

In [22]:
from src.sentiment import analyze_sentiment

In [ ]:
title_results = []
score_results = []

for title in headline_data["title"]:
    sentiment = analyze_sentiment(title)
    title_results.append(sentiment[0][0]["label"])
    score_results.append(sentiment[0][0]["score"])

In [ ]:
headline_data["label"] = title_results
headline_data["score"] = score_results
headline_data

,ticker,title,date,label,score
0,NVDA,D-Wave CEO says Nvidia should be 'shaking in t...,2026-04-14T18:02:49Z,neutral,0.991197
1,NVDA,D-Wave CEO on quantum computing's ChatGPT mome...,2026-04-14T15:23:50Z,neutral,0.999862
2,NVDA,"Amazon stock leads 9-day Mag 7 performance, Te...",2026-04-13T19:42:26Z,negative,0.998382
3,NVDA,Will the Iran War Cause a Recession? Here's Wh...,2026-04-14T19:03:49Z,negative,0.881226
4,NVDA,Why NextEra Energy Is a Safe Way to Invest in ...,2026-04-14T19:03:00Z,positive,0.988199
5,NVDA,"AI Stocks: What Bubble? CoreWeave, Nebius, Dat...",2026-04-14T19:02:28Z,negative,0.987412
6,NVDA,NVIDIA Rises Even as Quantum Computing Threat ...,2026-04-14T19:02:28Z,negative,0.883895
7,NVDA,Where Could Palantir Be in 3 Years? The Bear C...,2026-04-14T19:00:00Z,neutral,0.999843
8,NVDA,Why CarMax Stock Just Crashed,2026-04-14T18:53:47Z,negative,0.768828
9,NVDA,VWOB: The End of the Iran War Would Boost This...,2026-04-14T18:50:00Z,positive,0.999226
10,META,"Sandisk to join Nasdaq-100, CoreWeave stock su...",2026-04-13T18:09:23Z,positive,0.999137
11,META,"Amazon stock leads 9-day Mag 7 performance, Te...",2026-04-13T19:42:26Z,negative,0.998382
12,META,"AI Stocks: What Bubble? CoreWeave, Nebius, Dat...",2026-04-14T19:02:28Z,negative,0.987412
13,META,Why Advanced Micro Devices Shares Are Gaining ...,2026-04-14T16:51:46Z,positive,0.999208
14,META,TSMC Shows Where AI Demand is Headed,2026-04-14T16:22:00Z,neutral,0.999813
15,META,Feeling Burned Out on Tech Stocks? Buy SPYM,2026-04-14T16:20:00Z,negative,0.802791
16,META,Can Rising AI Demand Boost Arista's Future Gro...,2026-04-14T16:04:00Z,positive,0.999490
17,META,Meta Set to Surpass Google in Digital Ads,2026-04-14T16:01:54Z,positive,0.995286
18,META,Italy court allows class action against Meta o...,2026-04-14T15:57:49Z,neutral,0.997825
19,META,Here’s What CoreWeave’s (CRWV) Partnership Wit...,2026-04-14T15:56:17Z,neutral,0.999867
20,MSFT,Software stocks are finally joining the tech r...,2026-04-14T16:23:47Z,neutral,0.911115
21,MSFT,"Amazon stock leads 9-day Mag 7 performance, Te...",2026-04-13T19:42:26Z,negative,0.998382
22,MSFT,"AI Stocks: What Bubble? CoreWeave, Nebius, Dat...",2026-04-14T19:02:28Z,negative,0.987412
23,MSFT,Jim Cramer Notes “Microsoft’s Doing Terribly”,2026-04-14T18:14:28Z,negative,0.996050
24,MSFT,Is Microsoft (MSFT) Still Attractive After Rec...,2026-04-14T18:09:26Z,positive,0.997897
25,MSFT,Microsoft Raises Surface Prices as AI Costs Rise,2026-04-14T17:55:52Z,negative,0.991421
26,MSFT,Jim Cramer Shares Hot Take on Latest Analyst T...,2026-04-14T17:54:19Z,neutral,0.999817
27,MSFT,"Which Underperforming ""Magnificent Seven"" Stoc...",2026-04-14T17:20:00Z,positive,0.990096
28,MSFT,VivoPower appoints AI strategist Khadija Musta...,2026-04-14T17:07:41Z,neutral,0.999872
29,MSFT,Software Stocks Quietly Sold Off – Snap Up Thi...,2026-04-14T17:01:54Z,negative,0.964805
30,AMD,Why Advanced Micro Devices Shares Are Gaining ...,2026-04-14T16:51:46Z,positive,0.999208
31,AMD,AMD EPYC Powers AI Agent Workloads As CPUs Gai...,2026-04-14T15:04:31Z,neutral,0.994193
32,AMD,This Super Stock Could Be the Biggest Winner i...,2026-04-14T14:06:00Z,positive,0.768711
33,AMD,Chip Stocks Are on Pace for Their Longest Win ...,2026-04-14T13:39:13Z,positive,0.999401
34,AMD,Advanced Micro Devices (AMD) Stock at $250: Bu...,2026-04-14T13:25:01Z,neutral,0.999860
35,AMD,Meet the Super Semiconductor Stock Crushing Nv...,2026-04-14T13:20:00Z,neutral,0.976703
36,AMD,NVIDIA's AI Factory Vision: Can It Further Boo...,2026-04-14T12:38:00Z,positive,0.999506
37,AMD,AMD Is Where Nvidia was 4 Years Ago — This Is ...,2026-04-14T11:21:11Z,neutral,0.999832
38,AMD,"The Zacks Analyst Blog Highlights Eli Lilly, M...",2026-04-14T10:28:00Z,neutral,0.999886
39,AMD,Super Micro Extends Edge AI Reach With New AMD...,2026-04-14T03:08:29Z,positive,0.998249
40,GOOGL,Why Lowe's is investing in skilled trades and ...,2026-04-14T15:50:09Z,neutral,0.988876
41,GOOGL,"AI Stocks: What Bubble? CoreWeave, Nebius, Dat...",2026-04-14T19:02:28Z,negative,0.987412
42,GOOGL,"S&P 500, Nasdaq 100 Rally as Tech Gains Outwei...",2026-04-14T18:25:30Z,negative,0.987849
43,GOOGL,"Jim Cramer Says “Don’t Mess With Alphabet, The...",2026-04-14T18:14:31Z,negative,0.550895
44,GOOGL,Stock Market Today: Nasdaq Leads After Inflati...,2026-04-14T18:13:15Z,negative,0.983723
45,GOOGL,Alphabet Price Prediction: Bull and Bear Case,2026-04-14T18:07:43Z,neutral,0.999761
46,GOOGL,Here's Why Alphabet Shares Popped Today (And W...,2026-04-14T18:01:41Z,positive,0.999385
47,GOOGL,London gets closer to its first robotaxi servi...,2026-04-14T18:00:09Z,neutral,0.999470
48,GOOGL,Why This 97-Year-Old Fund Pays 8% Without Sacr...,2026-04-14T17:56:49Z,neutral,0.857556
49,GOOGL,"Pictet Loads Up MercadoLibre With 3,500 Shares...",2026-04-14T17:30:20Z,neutral,0.941445

In [ ]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322166  196.210236  259.299286  24.206573
2023-03-16  96.599998   99.497643  203.334335  269.810333  25.518410
2023-03-17  97.839996  100.787003  194.086884  272.965607  25.702248
2023-03-20  96.809998  100.390282  196.269775  265.932220  25.877092
2023-03-21  95.930000  104.059937  200.585892  267.446320  26.175825

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135444  196.240001  260.315235  24.264521  ...
2023-03-16  96.690002  100.360514  204.157874  270.161991  25.565367  ...
2023-03-17  98.750000  101.996996  200.327900  276.775377  26.375651  ...
2023-03-20  96.940002  100.915936  197.807710  271.060767  26.000983  ...
2023-03-21  99.459999  104.238461  201.965068  268.638097  26.368655  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455857  191.447607  253.965606  23.739986
2023-03-16  89.720001   95.411413  196.716272  259.074558  24.005749
2023-03-17  96.660004   99.438150  198.998337  271.822690  25.959020
2023-03-20  96.300003   99.299300  196.934557  270.572334  25.592345
2023-03-21  97.000000  100.420022  201.617787  268.520878  26.156843

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [ ]:
reshaped_data = df["Close"].stack().reset_index().rename(columns={0: "Close"})
reshaped_data.head()

        Date Ticker       Close
0 2023-03-15    AMD   89.680000
1 2023-03-15  GOOGL   95.322166
2 2023-03-15   META  196.210220
3 2023-03-15   MSFT  259.299225
4 2023-03-15   NVDA   24.206570

In [43]:
reshaped_data = reshaped_data.set_index('Date')

In [44]:
# Group data by months

# reshaped_data.dtypes

reshaped_data.groupby(["Ticker", pd.Grouper(freq='ME')])["Close"].mean()

Ticker  Date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
                         ...
NVDA    2025-11-30    187.962520
        2025-12-31    182.324673
        2026-01-31    186.711894
        2026-02-28    185.701528
        2026-03-31    182.350104
Name: Close, Length: 185, dtype: float64