In [1]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np

In [2]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [3]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [4]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322166  196.210236  259.299286  24.206573
2023-03-16  96.599998   99.497643  203.334335  269.810333  25.518410
2023-03-17  97.839996  100.787003  194.086884  272.965607  25.702248
2023-03-20  96.809998  100.390282  196.269775  265.932220  25.877092
2023-03-21  95.930000  104.059937  200.585892  267.446320  26.175825

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135444  196.240001  260.315235  24.264521  ...
2023-03-16  96.690002  100.360514  204.157874  270.161991  25.565367  ...
2023-03-17  98.750000  101.996996  200.327900  276.775377  26.375651  ...
2023-03-20  96.940002  100.915936  197.807710  271.060767  26.000983  ...
2023-03-21  99.459999  104.238461  201.965068  268.638097  26.368655  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455857  191.447607  253.965606  23.739986
2023-03-16  89.720001   95.411413  196.716272  259.074558  24.005749
2023-03-17  96.660004   99.438150  198.998337  271.822690  25.959020
2023-03-20  96.300003   99.299300  196.934557  270.572334  25.592345
2023-03-21  97.000000  100.420022  201.617787  268.520878  26.156843

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [5]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [6]:
df.shape

(752, 25)

In [7]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [8]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303726  510.032442  406.722718  110.174772
std      41.766704   59.267770  163.535075   64.594057   53.493754
min      78.209999   95.322166  194.086884  259.299286   24.206573
25%     112.002502  136.263779  335.286369  365.005585   48.840421
50%     141.760002  164.499840  524.088898  409.369659  116.998009
75%     169.445004  190.765568  645.484024  447.321579  146.969250
max     264.329987  343.448242  788.148987  539.825256  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249596  516.432463  410.145542  111.981672  ...
std      42.878968   60.022627  165.473901   64.914354   54.248785  ...
min      85.480003   96.135444  196.240001  260.315235   24.264521  ...
25%     114.395002  137.528318  337.253405  368.108833   49.556455  ...
50%     144.289993  165.989440  532.311036  412.460421  119.131438  ...
75%     172.049995  192.186486  652.566306  450.570331  148.926143  ...
max     267.079987  348.754481  794.384398  552.242002  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924468  178.153442  510.100256  406.707280  110.223178
std      41.941908   59.299622  164.119504   64.850847   53.622100
min      79.220001   92.455857  191.447607  253.965606   23.739986
25%     112.052500  136.271236  335.187151  364.869672   49.125126
50%     142.730003  164.479684  524.796338  410.068699  117.272929
75%     169.307503  190.554032  642.907274  446.764570  147.766453
max     264.190002  347.095646  789.296390  552.023241  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305591e+07  3.181655e+07  1.695474e+07  2.381806e+07  3.364204e+08
std     2.434066e+07  1.357632e+07  9.409263e+06  1.046421e+07  1.752086e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.670622e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [9]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  646.836182  409.410004  182.640106
2026-03-10  203.229996  307.040009  653.510498  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.299805  404.880005  186.029999
2026-03-12  197.740005  303.549988  637.634094  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.184998  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.195859  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  659.735149  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  658.556170  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  652.940997  406.119995  184.940002  ...
2026-03-13  199.679993  307.690002  628.631733  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.236984  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.000925  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.199915  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.195060  404.630005  184.050003
2026-03-13  198.110001  307.010010  623.356281  401.000000  184.919998

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27561900  23693100  18957600  26848000  160988400

[5 rows x 25 columns]

In [10]:
df["Low"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   86.220001   91.880610  189.354036  253.213401   23.339341
2023-03-16   89.019997   94.717154  194.563170  257.189215   23.872865
2023-03-17   95.940002   99.279458  193.908277  269.927568   25.645297
2023-03-20   92.900002   99.051349  192.132246  263.607275   25.107773
2023-03-21   93.639999  100.390270  196.408666  263.284862   25.358550
...                ...         ...         ...         ...         ...
2026-03-09  189.020004  294.079987  626.243828  403.500000  175.550494
2026-03-10  202.199997  305.570007  648.444828  402.929993  182.000149
2026-03-11  203.630005  305.920013  647.805365  401.589996  184.449997
2026-03-12  196.669998  301.029999  636.355221  401.709991  181.750000
2026-03-13  192.270004  300.440002  609.028522  394.250000  179.940002

[752 rows x 5 columns]

In [11]:
df["Low"]["NVDA"]

Date
2023-03-15     23.339341
2023-03-16     23.872865
2023-03-17     25.645297
2023-03-20     25.107773
2023-03-21     25.358550
                 ...
2026-03-09    175.550494
2026-03-10    182.000149
2026-03-11    184.449997
2026-03-12    181.750000
2026-03-13    179.940002
Name: NVDA, Length: 752, dtype: float64

In [12]:
(df == 0).any().sum()

np.int64(0)

In [13]:
df["Close"]
close_prices = df["Close"]

In [14]:
yf.Ticker("NVDA").news

[{'id': '8e31c4f5-b1b9-4121-bcde-c017591da237',
  'content': {'id': '8e31c4f5-b1b9-4121-bcde-c017591da237',
   'contentType': 'STORY',
   'title': "D-Wave CEO says Nvidia should be 'shaking in their boots' as quantum computing battles AI GPUs",
   'description': '',
   'summary': 'D-Wave touts massive energy efficiency gains over Nvidia as World Quantum Day sparks a sector-wide rally.',
   'pubDate': '2026-04-14T18:02:49Z',
   'displayTime': '2026-04-14T18:02:49Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/e29e2e10-3798-11f1-9ef7-e34a6abe0d8a',
    'originalWidth': 6694,
    'originalHeight': 4463,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/PTyIwlVEjq6PDsSbjIjOLA--~B/aD00NDYzO3c9NjY5NDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2026-04/e29e2e10-3798-11f1-9ef7-e34a6abe0d8a',
      'width': 6694,
      'height': 4463,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/_E3Ysg.am1vfxzVa7EvvlQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2026-04/e29e2e10-3798-11f1-9ef7-e34a6abe0d8a',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/d-wave-ceo-says-nvidia-should-be-shaking-in-their-boots-as-quantum-computing-battles-ai-gpus-180249321.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/d-wave-ceo-says-nvidia-should-be-shaking-in-their-boots-as-quantum-computing-battles-ai-gpus-180249321.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': '4d7fca51-e204-4f60-8696-b74b3803f426',
       'contentType': 'STORY',
       'isHosted': True,
       'title': 'Software stocks are finally joining the tech rally',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/f08ab6c0-3814-11f1-bff1-2a76a58609d7',
        'originalWidth': 5760,
        'originalHeight': 3240,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/news/software-stocks-are-finally-joining-the-tech-rally-162347655.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/software-stocks-are-finally-joining-the-tech-rally-162347655.html'}}},
     {'content': {'id': '60f69242-3c86-43ec-9eac-5d1c5699a8c1',
       'contentType': 'VIDEO',
       'isHosted': True,
       'title': "Why Lowe's is investing in skilled trades and partnering with Nvidia",
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2024-05/1b6e25a0-16e5-11ef-bd7f-747aab72c59f',
        'originalWidth': 5000,
        'originalHeight': 3334,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance Video',
        'sourceId': 'video.yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/video/why-lowes-is-investing-in-skilled-trades-and-partnering-with-nvidia-155009051.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/why-lowes-is-investing-in-skilled-trades-and-partnering-with-nvidia-155009051.html'}}}]}}},
 {'id': '8d6e9c25-36dc-4fa0-b110-6b864420836a',
  'content': {'id': '8d6e9c25-36dc-4fa0-b110-6b864420836a',
   'contentType': 'VIDEO',
   'title': "D-Wave CEO on quantum computing's ChatGPT moment, Nvidia, & more",
   'description': '<p>D-Wave Quantum (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/QBTS/" data-i13n="slk:QBTS;cpos:1;pos:1">QBTS</a>) president and CEO Alan Baratz sits down with Yahoo Finance Executive Editor Brian Sozzi to discuss Nvidia\'s (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/NVDA/" data-i13n="cpos:2;pos:1">NVDA</a>) artificial intelligence (AI) models for quantum computing, the future of the industry, and more.</p>',
   'summary': "D-Wave Quantum (QBTS) president and CEO Alan Baratz sits down with Yahoo Finance Executive Editor Brian Sozzi to discuss Nvidia's (NVDA) artificial intelligence (AI) models for quantum computing, the future of the industry, and more.",
   'pubDate': '2026-04-14T15:23:50Z',
   'displayTime': '',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/9GcP.RdUJvpsCZPJdHElHw--~B/aD0xNDEwO3c9MjUwNzthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/screenshot_2026-04-14_at_10.57.23_2190.png_08c761454f3dd30c5e1878f45db7dd88ae1b571558ccf19580030e84081a5e90.png',
    'originalWidth': 2507,
    'originalHeight': 1410,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/9GcP.RdUJvpsCZPJdHElHw--~B/aD0xNDEwO3c9MjUwNzthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/screenshot_2026-04-14_at_10.57.23_2190.png_08c761454f3dd30c5e1878f45db7dd88ae1b571558ccf19580030e84081a5e90.png',
      'width': 2507,
      'height': 1410,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/aj21Je0i_lgk6RNN.VUwUA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/screenshot_2026-04-14_at_10.57.23_2190.png_08c761454f3dd30c5e1878f45db7dd88ae1b571558ccf19580030e84081a5e90.png',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance Video',
    'url': 'https://finance.yahoo.com/',
    'sourceId': 'video.yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/video/d-wave-ceo-on-quantum-computings-chatgpt-moment-nvidia--more-152350565.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/d-wave-ceo-on-quantum-computings-chatgpt-moment-nvidia--more-152350565.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': '71222ea2-886e-4c99-a388-a24c2ef2c11b',
       'contentType': 'STORY',
       'isHosted': True,
       'title': 'AI trade is leading the stock market again: Chart of the Day',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/ddd012c0-376d-11f1-beec-98e5c6775bf5',
        'originalWidth': 5675,
        'originalHeight': 3784,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/news/ai-trade-is-leading-the-stock-market-again-chart-of-the-day-100044721.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/ai-trade-is-leading-the-stock-market-again-chart-of-the-day-100044721.html'}}},
     {'content': {'id': '959d62f7-7c31-4e6c-ac78-fd4578d0fce8',
       'contentType': 'VIDEO',
       'isHosted': True,
       'title': "Nvidia denies rumors that it's in acquisition talks with PC maker",
       'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/hpSWsY7R04K3Rnr4ISHxxw--~B/aD0xODUzO3c9MzI5NDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/90515a90-e786-11f0-99fe-0e8345c4333d_c2901fe95779a965796c697793f87c2839869391e5eaaaaffa724b48fc1ca2d5.com/creatr-uploaded-images/2026-01/90515a90-e786-11f0-99fe-0e8345c4333d',
        'originalWidth': 3294,
        'originalHeight': 1853,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance Video',
        'sourceId': 'video.yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/video/nvidia-denies-rumors-that-its-in-acquisition-talks-with-pc-maker-210613217.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/nvidia-denies-rumors-that-its-in-acquisition-talks-with-pc-maker-210613217.html'}}}]}}},
 {'id': '00de8b33-de86-42f7-8c1a-677a4f581e8e',
  'content': {'id': '00de8b33-de86-42f7-8c1a-677a4f581e8e',
   'contentType': 'VIDEO',
   'title': 'Amazon stock leads 9-day Mag 7 performance, Tesla falls behind',
   'description': '<p>Yahoo Finance Markets and Data Editor Jared Blikre takes a look at megacaps\' recent stock performance, including Big Tech names like Amazon (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/AMZN/" data-i13n="cpos:1;pos:1">AMZN</a>), Broadcom (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/AVGO/" data-i13n="cpos:2;pos:1">AVGO</a>), and Tesla (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/TSLA/" data-i13n="cpos:3;pos:1">TSLA</a>).</p>',
   'summary': "Yahoo Finance Markets and Data Editor Jared Blikre takes a look at megacaps' recent stock performance, including Big Tech names like Amazon (AMZN), Broadcom (AVGO), and Tesla (TSLA).",
   'pubDate': '2026-04-13T19:42:26Z',
   'displayTime': '',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/Z6jmgstRIJEss5uBm.6yPA--~B/aD0yODEyO3c9NTAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/cb6b4ae5-1494-4377-aa66-0a11445a0a0e_576cacbf7cbdafaf33e2818cfaeb0ecbe9e82d780ea791d388892991b5044df0.net/images/2026-04/cb6b4ae5-1494-4377-aa66-0a11445a0a0e',
    'originalWidth': 5000,
    'originalHeight': 2812,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Z6jmgstRIJEss5uBm.6yPA--~B/aD0yODEyO3c9NTAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/cb6b4ae5-1494-4377-aa66-0a11445a0a0e_576cacbf7cbdafaf33e2818cfaeb0ecbe9e82d780ea791d388892991b5044df0.net/images/2026-04/cb6b4ae5-1494-4377-aa66-0a11445a0a0e',
      'width': 5000,
      'height': 2812,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/KpKCQ4ibK5yoXOq_v9Kf.w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/cb6b4ae5-1494-4377-aa66-0a11445a0a0e_576cacbf7cbdafaf33e2818cfaeb0ecbe9e82d780ea791d388892991b5044df0.net/images/2026-04/cb6b4ae5-1494-4377-aa66-0a11445a0a0e',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance Video',
    'url': 'https://finance.yahoo.com/',
    'sourceId': 'video.yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/video/amazon-stock-leads-9-day-mag-7-performance-tesla-falls-behind-194226931.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/amazon-stock-leads-9-day-mag-7-performance-tesla-falls-behind-194226931.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '0f0f3857-bdb7-3ab0-bdae-7a6f2ab890e8',
  'content': {'id': '0f0f3857-bdb7-3ab0-bdae-7a6f2ab890e8',
   'contentType': 'STORY',
   'title': "Will the Iran War Cause a Recession? Here's What It Would Take, According to Wall Street",
   'description': '',
   'summary': 'The Iran war is expected to slow global economic growth, but a recession seems unlikely.',
   'pubDate': '2026-04-14T19:03:49Z',
   'displayTime': '2026-04-14T19:03:49Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/c5228439407eca2f645ed285d9adc424',
    'originalWidth': 1200,
    'originalHeight': 801,
    'caption': 'An arrow going down a blackboard with words like "recession" written next to it.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/EzhvkCS7MDH8Dy8ZXTISFQ--~B/aD04MDE7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/c5228439407eca2f645ed285d9adc424',
      'width': 1200,
      'height': 801,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/cBjMg8EpgyumKOFao7HJjQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/c5228439407eca2f645ed285d9adc424',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/14/will-the-iran-war-cause-a-recession-heres-what-it/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/economy/articles/iran-war-cause-recession-heres-190349663.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '845efe72-518d-35ed-9999-00fe9caddd33',
  'content': {'id': '845efe72-518d-35ed-9999-00fe9caddd33',
   'contentType': 'STORY',
   'title': 'Why NextEra Energy Is a Safe Way to Invest in the Solar Energy Boom',
   'description': '',
   'summary': 'Solar is scaling rapidly across the U.S., and NextEra Energy offers exposure with built-in stability.',
   'pubDate': '2026-04-14T19:03:00Z',
   'displayTime': '2026-04-14T19:03:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/caee470c20b4de309bbb38df1a5b15ae',
    'originalWidth': 600,
    'originalHeight': 400,
    'caption': 'An engineer working on solar panels.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/4bhNraX_1RFEYQ6guvo.4g--~B/aD00MDA7dz02MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/caee470c20b4de309bbb38df1a5b15ae',
      'width': 600,
      'height': 400,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/EEp9CoqVC9_lVTicqgk8VA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/caee470c20b4de309bbb38df1a5b15ae',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/14/why-nextera-energy-is-a-safe-way-to-invest-in-the/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/energy/articles/why-nextera-energy-safe-way-190300362.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'f63972ac-d76e-32fd-8d05-7f1a60a8d3c8',
  'content': {'id': 'f63972ac-d76e-32fd-8d05-7f1a60a8d3c8',
   'contentType': 'STORY',
   'title': 'AI Stocks: What Bubble? CoreWeave, Nebius, Data Center Plays Surge Amid Compute Shortage',
   'description': '',
   'summary': 'Leaders and laggards in artificial intelligence stocks keep evolving with CoreWeave and Nebius among top gainers with Q1 earnings due.',
   'pubDate': '2026-04-14T19:02:28Z',
   'displayTime': '2026-04-14T19:02:28Z',
   'isHosted': False,
   'bypassModal': False,
   'previewUrl': 'https://finance.yahoo.com/m/f63972ac-d76e-32fd-8d05-7f1a60a8d3c8/ai-stocks-what-bubble-.html',
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/ibd.com/d7cf9ddd4d7e16b4173298be6f3ba2a3',
    'originalWidth': 1000,
    'originalHeight': 565,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/vm6FVjWkOuw1cZ7OX4Tyxw--~B/aD01NjU7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/d7cf9ddd4d7e16b4173298be6f3ba2a3',
      'width': 1000,
      'height': 565,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/lNWbO7ZCcoH85acWTw0D9A--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/ibd.com/d7cf9ddd4d7e16b4173298be6f3ba2a3',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': "Investor's Business Daily",
    'url': 'http://www.investors.com/',
    'sourceId': 'ibd.com'},
   'canonicalUrl': {'url': 'https://www.investors.com/news/technology/ai-stocks-artificial-intelligence-stocks-2026-leaders-laggards-april13/?src=A00220&yptr=yahoo',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': None,
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '18b7996a-4621-3048-9e1e-786b35716e7e',
  'content': {'id': '18b7996a-4621-3048-9e1e-786b35716e7e',
   'contentType': 'STORY',
   'title': 'NVIDIA Rises Even as Quantum Computing Threat Looms and Insider Selling Sparks Debate',
   'description': '',
   'summary': 'NVIDIA (NASDAQ:NVDA) shares are up 3% today, rising from $189.31 to $195 as of midday Tuesday. The move adds to a strong run, with NVDA stock up 76% over the past year. That’s a remarkable climb for a stock that’s now sitting on a market cap of roughly $4.73 trillion. Today’s session brings a mix ... NVIDIA Rises Even as Quantum Computing Threat Looms and Insider Selling Sparks Debate',
   'pubDate': '2026-04-14T19:02:28Z',
   'displayTime': '2026-04-14T19:02:28Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/8afb5921814fb90f2b3aad3cf87cb781',
    'originalWidth': 2560,
    'originalHeight': 1708,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/MVp7kplSyLXmfZT78Mtm2Q--~B/aD0xNzA4O3c9MjU2MDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/24_7_wall_st__718/8afb5921814fb90f2b3aad3cf87cb781',
      'width': 2560,
      'height': 1708,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/KUZEkt2otvMBZNf_3IGv2g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/8afb5921814fb90f2b3aad3cf87cb781',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/04/14/nvidia-rises-even-as-quantum-computing-threat-looms-and-insider-selling-sparks-debate/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/nvidia-rises-even-quantum-computing-190228105.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '727d67d8-0562-33d6-b83e-5b508cca9d71',

In [15]:
headlines = []

for stock in stocks:
    news = yf.Ticker(stock).news
    for article in news:
        headlines.append({
            "ticker": stock,
            "title": article["content"]["title"],
            "date": article["content"]["pubDate"]
        })

In [16]:
# Show all content and metadata for single headline
yf.Ticker("NVDA").news[0]

{'id': '8e31c4f5-b1b9-4121-bcde-c017591da237',
 'content': {'id': '8e31c4f5-b1b9-4121-bcde-c017591da237',
  'contentType': 'STORY',
  'title': "D-Wave CEO says Nvidia should be 'shaking in their boots' as quantum computing battles AI GPUs",
  'description': '',
  'summary': 'D-Wave touts massive energy efficiency gains over Nvidia as World Quantum Day sparks a sector-wide rally.',
  'pubDate': '2026-04-14T18:02:49Z',
  'displayTime': '2026-04-14T18:02:49Z',
  'isHosted': True,
  'bypassModal': False,
  'previewUrl': None,
  'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/e29e2e10-3798-11f1-9ef7-e34a6abe0d8a',
   'originalWidth': 6694,
   'originalHeight': 4463,
   'caption': '',
   'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/PTyIwlVEjq6PDsSbjIjOLA--~B/aD00NDYzO3c9NjY5NDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2026-04/e29e2e10-3798-11f1-9ef7-e34a6abe0d8a',
     'width': 6694,
     'height': 4463,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/_E3Ysg.am1vfxzVa7EvvlQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2026-04/e29e2e10-3798-11f1-9ef7-e34a6abe0d8a',
     'width': 170,
     'height': 128,
     'tag': '170x128'}]},
  'provider': {'displayName': 'Yahoo Finance',
   'url': 'http://finance.yahoo.com/',
   'sourceId': 'yahoofinance.com'},
  'canonicalUrl': {'url': 'https://finance.yahoo.com/news/d-wave-ceo-says-nvidia-should-be-shaking-in-their-boots-as-quantum-computing-battles-ai-gpus-180249321.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/d-wave-ceo-says-nvidia-should-be-shaking-in-their-boots-as-quantum-computing-battles-ai-gpus-180249321.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'metadata': {'editorsPick': True},
  'finance': {'premiumFinance': {'isPremiumNews': False,
    'isPremiumFreeNews': False}},
  'storyline': {'storylineItems': [{'content': {'id': '4d7fca51-e204-4f60-8696-b74b3803f426',
      'contentType': 'STORY',
      'isHosted': True,
      'title': 'Software stocks are finally joining the tech rally',
      'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/f08ab6c0-3814-11f1-bff1-2a76a58609d7',
       'originalWidth': 5760,
       'originalHeight': 3240,
       'caption': '',
       'resolutions': None},
      'provider': {'displayName': 'Yahoo Finance',
       'sourceId': 'yahoofinance.com'},
      'previewUrl': None,
      'providerContentUrl': '',
      'canonicalUrl': {'url': 'https://finance.yahoo.com/news/software-stocks-are-finally-joining-the-tech-rally-162347655.html'},
      'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/software-stocks-are-finally-joining-the-tech-rally-162347655.html'}}},
    {'content': {'id': '60f69242-3c86-43ec-9eac-5d1c5699a8c1',
      'contentType': 'VIDEO',
      'isHosted': True,
      'title': "Why Lowe's is investing in skilled trades and partnering with Nvidia",
      'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2024-05/1b6e25a0-16e5-11ef-bd7f-747aab72c59f',
       'originalWidth': 5000,
       'originalHeight': 3334,
       'caption': '',
       'resolutions': None},
      'provider': {'displayName': 'Yahoo Finance Video',
       'sourceId': 'video.yahoofinance.com'},
      'previewUrl': None,
      'providerContentUrl': '',
      'canonicalUrl': {'url': 'https://finance.yahoo.com/video/why-lowes-is-investing-in-skilled-trades-and-partnering-with-nvidia-155009051.html'},
      'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/why-lowes-is-investing-in-skilled-trades-and-partnering-with-nvidia-155009051.html'}}}]}}}

In [17]:
headlines[0]

{'ticker': 'NVDA',
 'title': "D-Wave CEO says Nvidia should be 'shaking in their boots' as quantum computing battles AI GPUs",
 'date': '2026-04-14T18:02:49Z'}

In [18]:
len(headlines)

50

In [19]:
headline_data = pd.DataFrame(headlines)

In [20]:
headline_data.head()

,ticker,title,date
0,NVDA,D-Wave CEO says Nvidia should be 'shaking in t...,2026-04-14T18:02:49Z
1,NVDA,D-Wave CEO on quantum computing's ChatGPT mome...,2026-04-14T15:23:50Z
2,NVDA,"Amazon stock leads 9-day Mag 7 performance, Te...",2026-04-13T19:42:26Z
3,NVDA,Will the Iran War Cause a Recession? Here's Wh...,2026-04-14T19:03:49Z
4,NVDA,Why NextEra Energy Is a Safe Way to Invest in ...,2026-04-14T19:03:00Z

In [21]:
from src.sentiment import analyze_sentiment

In [ ]:
analyze_sentiment()

[[{'label': 'neutral', 'score': 0.999840497970581},
  {'label': 'negative', 'score': 0.00010046921670436859},
  {'label': 'positive', 'score': 5.9057514590676874e-05}]]

In [ ]:
title_results = []
score_results = []

for title in headline_data["title"]:
    sentiment = analyze_sentiment(title)
    title_results.append(sentiment[0][0]["label"])
    score_results.append(sentiment[0][0]["score"])

In [28]:
headline_data["label"] = title_results
headline_data["score"] = score_results
headline_data

,ticker,title,date,label,score
0,NVDA,D-Wave CEO says Nvidia should be 'shaking in t...,2026-04-14T18:02:49Z,neutral,0.991197
1,NVDA,D-Wave CEO on quantum computing's ChatGPT mome...,2026-04-14T15:23:50Z,neutral,0.999862
2,NVDA,"Amazon stock leads 9-day Mag 7 performance, Te...",2026-04-13T19:42:26Z,negative,0.998382
3,NVDA,Will the Iran War Cause a Recession? Here's Wh...,2026-04-14T19:03:49Z,negative,0.881226
4,NVDA,Why NextEra Energy Is a Safe Way to Invest in ...,2026-04-14T19:03:00Z,positive,0.988199
5,NVDA,"AI Stocks: What Bubble? CoreWeave, Nebius, Dat...",2026-04-14T19:02:28Z,negative,0.987412
6,NVDA,NVIDIA Rises Even as Quantum Computing Threat ...,2026-04-14T19:02:28Z,negative,0.883895
7,NVDA,Where Could Palantir Be in 3 Years? The Bear C...,2026-04-14T19:00:00Z,neutral,0.999843
8,NVDA,Why CarMax Stock Just Crashed,2026-04-14T18:53:47Z,negative,0.768828
9,NVDA,VWOB: The End of the Iran War Would Boost This...,2026-04-14T18:50:00Z,positive,0.999226
10,META,"Sandisk to join Nasdaq-100, CoreWeave stock su...",2026-04-13T18:09:23Z,positive,0.999137
11,META,"Amazon stock leads 9-day Mag 7 performance, Te...",2026-04-13T19:42:26Z,negative,0.998382
12,META,"AI Stocks: What Bubble? CoreWeave, Nebius, Dat...",2026-04-14T19:02:28Z,negative,0.987412
13,META,Why Advanced Micro Devices Shares Are Gaining ...,2026-04-14T16:51:46Z,positive,0.999208
14,META,TSMC Shows Where AI Demand is Headed,2026-04-14T16:22:00Z,neutral,0.999813
15,META,Feeling Burned Out on Tech Stocks? Buy SPYM,2026-04-14T16:20:00Z,negative,0.802791
16,META,Can Rising AI Demand Boost Arista's Future Gro...,2026-04-14T16:04:00Z,positive,0.999490
17,META,Meta Set to Surpass Google in Digital Ads,2026-04-14T16:01:54Z,positive,0.995286
18,META,Italy court allows class action against Meta o...,2026-04-14T15:57:49Z,neutral,0.997825
19,META,Here’s What CoreWeave’s (CRWV) Partnership Wit...,2026-04-14T15:56:17Z,neutral,0.999867
20,MSFT,Software stocks are finally joining the tech r...,2026-04-14T16:23:47Z,neutral,0.911115
21,MSFT,"Amazon stock leads 9-day Mag 7 performance, Te...",2026-04-13T19:42:26Z,negative,0.998382
22,MSFT,"AI Stocks: What Bubble? CoreWeave, Nebius, Dat...",2026-04-14T19:02:28Z,negative,0.987412
23,MSFT,Jim Cramer Notes “Microsoft’s Doing Terribly”,2026-04-14T18:14:28Z,negative,0.996050
24,MSFT,Is Microsoft (MSFT) Still Attractive After Rec...,2026-04-14T18:09:26Z,positive,0.997897
25,MSFT,Microsoft Raises Surface Prices as AI Costs Rise,2026-04-14T17:55:52Z,negative,0.991421
26,MSFT,Jim Cramer Shares Hot Take on Latest Analyst T...,2026-04-14T17:54:19Z,neutral,0.999817
27,MSFT,"Which Underperforming ""Magnificent Seven"" Stoc...",2026-04-14T17:20:00Z,positive,0.990096
28,MSFT,VivoPower appoints AI strategist Khadija Musta...,2026-04-14T17:07:41Z,neutral,0.999872
29,MSFT,Software Stocks Quietly Sold Off – Snap Up Thi...,2026-04-14T17:01:54Z,negative,0.964805
30,AMD,Why Advanced Micro Devices Shares Are Gaining ...,2026-04-14T16:51:46Z,positive,0.999208
31,AMD,AMD EPYC Powers AI Agent Workloads As CPUs Gai...,2026-04-14T15:04:31Z,neutral,0.994193
32,AMD,This Super Stock Could Be the Biggest Winner i...,2026-04-14T14:06:00Z,positive,0.768711
33,AMD,Chip Stocks Are on Pace for Their Longest Win ...,2026-04-14T13:39:13Z,positive,0.999401
34,AMD,Advanced Micro Devices (AMD) Stock at $250: Bu...,2026-04-14T13:25:01Z,neutral,0.999860
35,AMD,Meet the Super Semiconductor Stock Crushing Nv...,2026-04-14T13:20:00Z,neutral,0.976703
36,AMD,NVIDIA's AI Factory Vision: Can It Further Boo...,2026-04-14T12:38:00Z,positive,0.999506
37,AMD,AMD Is Where Nvidia was 4 Years Ago — This Is ...,2026-04-14T11:21:11Z,neutral,0.999832
38,AMD,"The Zacks Analyst Blog Highlights Eli Lilly, M...",2026-04-14T10:28:00Z,neutral,0.999886
39,AMD,Super Micro Extends Edge AI Reach With New AMD...,2026-04-14T03:08:29Z,positive,0.998249
40,GOOGL,Why Lowe's is investing in skilled trades and ...,2026-04-14T15:50:09Z,neutral,0.988876
41,GOOGL,"AI Stocks: What Bubble? CoreWeave, Nebius, Dat...",2026-04-14T19:02:28Z,negative,0.987412
42,GOOGL,"S&P 500, Nasdaq 100 Rally as Tech Gains Outwei...",2026-04-14T18:25:30Z,negative,0.987849
43,GOOGL,"Jim Cramer Says “Don’t Mess With Alphabet, The...",2026-04-14T18:14:31Z,negative,0.550895
44,GOOGL,Stock Market Today: Nasdaq Leads After Inflati...,2026-04-14T18:13:15Z,negative,0.983723
45,GOOGL,Alphabet Price Prediction: Bull and Bear Case,2026-04-14T18:07:43Z,neutral,0.999761
46,GOOGL,Here's Why Alphabet Shares Popped Today (And W...,2026-04-14T18:01:41Z,positive,0.999385
47,GOOGL,London gets closer to its first robotaxi servi...,2026-04-14T18:00:09Z,neutral,0.999470
48,GOOGL,Why This 97-Year-Old Fund Pays 8% Without Sacr...,2026-04-14T17:56:49Z,neutral,0.857556
49,GOOGL,"Pictet Loads Up MercadoLibre With 3,500 Shares...",2026-04-14T17:30:20Z,neutral,0.941445