In [1]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np

In [2]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [3]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [4]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322166  196.210251  259.299316  24.206570
2023-03-16  96.599998   99.497665  203.334320  269.810394  25.518408
2023-03-17  97.839996  100.786995  194.086899  272.965637  25.702246
2023-03-20  96.809998  100.390274  196.269775  265.932190  25.877094
2023-03-21  95.930000  104.059952  200.585892  267.446350  26.175827

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135444  196.240016  260.315265  24.264517  ...
2023-03-16  96.690002  100.360537  204.157859  270.162052  25.565365  ...
2023-03-17  98.750000  101.996988  200.327916  276.775408  26.375649  ...
2023-03-20  96.940002  100.915928  197.807710  271.060735  26.000985  ...
2023-03-21  99.459999  104.238477  201.965068  268.638128  26.368657  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455857  191.447622  253.965636  23.739982
2023-03-16  89.720001   95.411435  196.716257  259.074617  24.005747
2023-03-17  96.660004   99.438143  198.998353  271.822721  25.959018
2023-03-20  96.300003   99.299293  196.934557  270.572303  25.592346
2023-03-21  97.000000  100.420037  201.617787  268.520909  26.156845

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [5]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [6]:
df.shape

(752, 25)

In [7]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [8]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303727  510.032443  406.722717  110.174772
std      41.766704   59.267769  163.535075   64.594056   53.493754
min      78.209999   95.322166  194.086899  259.299316   24.206570
25%     112.002502  136.263786  335.286377  365.005585   48.840424
50%     141.760002  164.499840  524.088867  409.369675  116.998009
75%     169.445004  190.765560  645.484024  447.321587  146.969254
max     264.329987  343.448242  788.148987  539.825195  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249597  516.432464  410.145542  111.981672  ...
std      42.878968   60.022627  165.473901   64.914352   54.248785  ...
min      85.480003   96.135444  196.240016  260.315265   24.264517  ...
25%     114.395002  137.528329  337.253419  368.108833   49.556456  ...
50%     144.289993  165.989432  532.311052  412.460406  119.131434  ...
75%     172.049995  192.186490  652.566306  450.570323  148.926131  ...
max     267.079987  348.754481  794.384398  552.241938  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924468  178.153442  510.100257  406.707280  110.223178
std      41.941908   59.299621  164.119504   64.850846   53.622100
min      79.220001   92.455857  191.447622  253.965636   23.739982
25%     112.052500  136.271236  335.187127  364.869620   49.125134
50%     142.730003  164.479676  524.796307  410.068699  117.272922
75%     169.307503  190.554043  642.907290  446.764548  147.766449
max     264.190002  347.095646  789.296390  552.023177  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305591e+07  3.181655e+07  1.695474e+07  2.381806e+07  3.364204e+08
std     2.434066e+07  1.357632e+07  9.409263e+06  1.046421e+07  1.752086e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.670622e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [9]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  646.836182  409.410004  182.640106
2026-03-10  203.229996  307.040009  653.510498  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.299805  404.880005  186.029999
2026-03-12  197.740005  303.549988  637.634094  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.184998  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.195859  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  659.735149  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  658.556170  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  652.940997  406.119995  184.940002  ...
2026-03-13  199.679993  307.690002  628.631733  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.236984  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.000925  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.199915  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.195060  404.630005  184.050003
2026-03-13  198.110001  307.010010  623.356281  401.000000  184.919998

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27561900  23693100  18957600  26848000  160988400

[5 rows x 25 columns]

In [10]:
df["Low"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   86.220001   91.880610  189.354051  253.213430   23.339337
2023-03-16   89.019997   94.717176  194.563156  257.189273   23.872863
2023-03-17   95.940002   99.279451  193.908292  269.927599   25.645295
2023-03-20   92.900002   99.051342  192.132246  263.607245   25.107775
2023-03-21   93.639999  100.390284  196.408666  263.284892   25.358552
...                ...         ...         ...         ...         ...
2026-03-09  189.020004  294.079987  626.243828  403.500000  175.550494
2026-03-10  202.199997  305.570007  648.444828  402.929993  182.000149
2026-03-11  203.630005  305.920013  647.805365  401.589996  184.449997
2026-03-12  196.669998  301.029999  636.355221  401.709991  181.750000
2026-03-13  192.270004  300.440002  609.028522  394.250000  179.940002

[752 rows x 5 columns]

In [11]:
df["Low"]["NVDA"]

Date
2023-03-15     23.339337
2023-03-16     23.872863
2023-03-17     25.645295
2023-03-20     25.107775
2023-03-21     25.358552
                 ...
2026-03-09    175.550494
2026-03-10    182.000149
2026-03-11    184.449997
2026-03-12    181.750000
2026-03-13    179.940002
Name: NVDA, Length: 752, dtype: float64

In [12]:
(df == 0).any().sum()

np.int64(0)

In [13]:
df["Close"]
close_prices = df["Close"]

In [ ]:
yf.Ticker("NVDA").news

In [20]:
headlines = []

for stock in stocks:
    news = yf.Ticker(stock).news
    for article in news:
        headlines.append({
            "ticker": stock,
            "title": article["content"]["title"],
            "date": article["content"]["pubDate"]
        })

In [ ]:
# Show all content and metadata for single headline
yf.Ticker("NVDA").news[0]

In [ ]:
headlines[0]

In [ ]:
len(headlines)

In [27]:
headline_data = pd.DataFrame(headlines)

In [28]:
headline_data.head()

,ticker,title,date
0,NVDA,Mag 7 needs Q2 revenue growth in order to 'jus...,2026-04-06T19:56:12Z
1,NVDA,Why Aehr Test Systems Stock Is Skyrocketing Today,2026-04-06T19:53:42Z
2,NVDA,Why Micron Stock Is Sinking Today,2026-04-06T19:36:14Z
3,NVDA,Boeing's Record Backlog and New Vietnam Orders...,2026-04-06T19:35:00Z
4,NVDA,Nvidia acquisition of SchedMD sparks worry amo...,2026-04-06T19:33:11Z