In [15]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np

In [16]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [17]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [18]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322159  196.378235  259.299225  24.206570
2023-03-16  96.599998   99.497658  203.508438  269.810425  25.518412
2023-03-17  97.839996  100.787010  194.253082  272.965637  25.702250
2023-03-20  96.809998  100.390282  196.437820  265.932251  25.877090
2023-03-21  95.930000  104.059944  200.757660  267.446350  26.175827

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135437  196.408026  260.315173  24.264517  ...
2023-03-16  96.690002  100.360529  204.332682  270.162082  25.565369  ...
2023-03-17  98.750000  101.997003  200.499443  276.775408  26.375653  ...
2023-03-20  96.940002  100.915936  197.977071  271.060798  26.000981  ...
2023-03-21  99.459999  104.238469  202.138017  268.638128  26.368657  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455850  191.611529  253.965547  23.739982
2023-03-16  89.720001   95.411427  196.884708  259.074646  24.005751
2023-03-17  96.660004   99.438158  199.168742  271.822721  25.959022
2023-03-20  96.300003   99.299300  197.103171  270.572365  25.592343
2023-03-21  97.000000  100.420030  201.790439  268.520909  26.156845

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [19]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [20]:
df.shape

(752, 25)

In [22]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [23]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303726  510.469119  406.722716  110.174772
std      41.766704   59.267770  163.675089   64.594057   53.493754
min      78.209999   95.322159  194.253082  259.299225   24.206570
25%     112.002502  136.263779  335.573380  365.005562   48.840419
50%     141.760002  164.499832  524.537567  409.369659  116.998013
75%     169.445004  190.765572  646.036697  447.321587  146.969254
max     264.329987  343.448242  788.823792  539.825256  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249497  516.874620  410.145541  111.981672  ...
std      42.878968   60.022415  165.615575   64.914353   54.248785  ...
min      85.480003   96.135437  196.408026  260.315173   24.264517  ...
25%     114.395002  137.528306  337.542174  368.108802   49.556452  ...
50%     144.289993  165.989440  532.766785  412.460391  119.131438  ...
75%     172.049995  192.186490  653.125000  450.570300  148.926147  ...
max     267.079987  348.754481  795.064526  552.242002  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924475  178.153668  510.536167  406.706907  110.223165
std      41.941916   59.300114  164.259450   64.850881   53.622082
min      79.220001   92.455850  191.611529  253.965547   23.739982
25%     112.052500  136.271221  335.474109  364.869672   49.125130
50%     142.730003  164.479684  525.245602  410.068683  117.272922
75%     169.307503  190.554043  643.457721  446.764548  147.766464
max     264.190002  347.095646  789.972167  552.023241  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305591e+07  3.181655e+07  1.695474e+07  2.381740e+07  3.364204e+08
std     2.434066e+07  1.357632e+07  9.409263e+06  1.046404e+07  1.752086e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.668590e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [24]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  647.390015  409.410004  182.640106
2026-03-10  203.229996  307.040009  654.070007  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.859985  404.880005  186.029999
2026-03-12  197.740005  303.549988  638.179993  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.710022  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.750000  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  660.299988  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  659.119995  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  653.500000  406.119995  184.940002  ...
2026-03-13  199.679993  307.614990  629.169922  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.780029  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.559998  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.760010  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.750000  404.630005  184.050003
2026-03-13  198.115005  307.179993  623.270020  400.720001  184.910004

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27561888  23693092  18957637  26350249  160988424

[5 rows x 25 columns]